### ISSUE TITLE
codeberg.org 

### ISSUE THREAD

**Issue by ibinshoid** [martok/palefill#78] opened 2023-01-15 11:35 UTC
When i open some pages on codeberg.org, like 'https://codeberg.org/explore/repos' i get some javascript-errors on top of the site.
it seems like palemoon doesn't support 'import' in javascript.
Can this be implemented by palefill?

**Comment by martok** [comment] 2023-01-15 14:39
(Due to the dynamic import) Duplicate of #34.

**Closed by martok** 2023-01-15 14:39 UTC
Labels: js-syntax, cantfix
