### ISSUE TITLE
Add support for Notion.Site

### ISSUE THREAD

**Issue by Symbian9** [martok/palefill#4] opened 2022-03-11 17:28 UTC
### System Details

- **OS/Platform:** Linux / Debian 10 stretch
- **Pale Moon version:** `29.4.4`

### Actual Behavior

Notion site is just shown in *Pale Moon* as blank white page:

- https://djinni.notion.site/Remote-tech-jobs-for-Ukraine-b7f0f216ca6a419e920b5bc8a0489949

Thanks to @Vangelis66 https://github.com/JustOff/github-wc-polyfill/issues/56#issuecomment-1064673764, I found that issue seems like related to the next:

```
SyntaxError: missing ( after for    app-6eec4a2fbd5acba8d6d3.js:1:550761
```

**Comment by martok** [comment] 2022-03-11 18:26
Is Notion even usable in UXP? When I used it last, it was so incredibly slow that I didn't even try anymore.

The domain name pattern is `{username}.notion.site` as well as `notion.so`, right?

**Comment by Symbian9** [comment] 2022-03-11 18:41
> The domain name pattern is `{username}.notion.site` as well as `notion.so`, right?

Yes.

**Comment by martok** [comment] 2022-03-11 19:24
Hrm. Four observations:

1. The column number has nothing to do with where the error is, there are plenty instances before that...
2. A 5.5 MB source file (what the hell) breaks Notepad++ :D
3. The problem is `for-await-of`, where I don't immediately see how this could be fixed/shimmed. I am actually baffled that UXP supports `async function *` generators but not the iterator you need to do something useful with them.
4. If it was possible, the fix rule matcher needs to be extended for domain wildcards.

**Comment by martok** [comment] 2022-06-15 22:44
> * The problem is `for-await-of`, sadly I don't immediately see how this could be fixed/shimmed. I am actually baffled that UXP supports `async function*` generators but not the iterator you need to do something useful with them.

Interesting: according to the changelogs, PM 28.9.0 implemented for-await loops, and now I'm getting error messages that look very different. Looks like an actual bug in UXP :eyes: 

From notions app.js, reduced to MWE:

```js
class xx {
  async *mapAsyncIterable(e, t) {
    yield await Promise.race(42);
  }
}
// SyntaxError: await is only valid in async functions
```
But:
```js
  async function* mapAsyncIterable(e, t) {
    yield await Promise.race(42);
  }
// OK
```
Since this is literally the same thing except bound to a prototype in the class declaration, it should work. Seems something in the class parser forgets to apply the async flag.

**Comment by martok** [comment] 2022-06-19 22:33
Just verified the above: once [UXP#1924](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1924) or something to that effect lands, one easy JS fix gets it working :)

**Comment by Vangelis66** [comment] 2022-06-27 00:05
> once [UXP#1924](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1924) or something to that effect lands, one easy JS fix gets it working

... Great news! 🎉 
Last Saturday's (25/06/2022) **UXP** releases by **roytam1** have [official UXP PR#1924](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1924/commits) merged in: 

https://github.com/roytam1/UXP/compare/5dc15ae641...e9cc7313ac

I have thus updated to latest **Serpent 52.9.0** (32-bit) build (buildID=20220623012013) and I can confirm your PR/code allows the browser to successfully load `*notion.*` URLs, whereas before it would only yield blank tabs 😞 ... So, many thanks for the platform "fix" you contributed! 🥇 

It's worth noting that the `*notion.*` URLs now load even without `palefill`, but just to check I installed the latest snapshot of the `4-notion` branch, i.e. `palefill-v1.14-1-git-20220619-g7a21c47`; my most used notion URI (and my test case here) is: 
https://www.notion.so/34dc4ddf501a4b98b46ea9fb4f3470af?v=878345c5d88f4d21a6520db752b5c29f
As said, the URI loads, but in `Web Console` I still see Syntax Errors: 

![notion](https://user-images.githubusercontent.com/9669492/175838458-2c3d5426-ca47-44be-bf4a-cc0c2ee633f1.JPG)

relating to scripts: 
```
https://www.notion.so/postRender-9a933ef3d3df311053da.js
https://www.notion.so/app-f0bafd74510cb698ce7e.js
```
So, is the "**.so**" TLD not supported by the `4-notion` **palefill** branch?

Your overall efforts are being greatly appreciated here... 😄

**Comment by martok** [comment] 2022-06-27 09:13
> EDIT:
> 
> ```diff
> -*.notion.site/postRender-*.js$script
> +*.notion.*/postRender-*.js$script
> ```

Jup, that. Or rather:
```diff
 *.notion.site/postRender-*.js$script
+www.notion.so/postRender-*.js$script
```
Which is much faster in the rule match engine.

I *thought* there was some on their own domain, but didn't find it immediately. That will be a thing to keep in mind when I merge this for real.

**Comment by martok** [comment] 2022-08-03 21:38
Confirmed working in Pale Moon 31.2.0.1, UXP 5.2.0 :)

**Closed** 2022-08-03 21:37 UTC
Labels: js-syntax

**Comment by Vangelis66** [comment] 2023-01-04 22:24
An **update** on the current state of `*.notion.*` support: 

The previous time I accessed my "notion test-case URL", 
https://www.notion.so/34dc4ddf501a4b98b46ea9fb4f3470af?v=878345c5d88f4d21a6520db752b5c29f,
was **mid-December** (last year); it loaded **fine** with the then current `palefill` version... 

Today, with `palefill-v1.25-4-git-20221228-g9674444` installed, that URL **fails to load** (constantly spinning centre circle) on a **slightly older UXP platform Serpent 52**: 

![notion1-st52](https://user-images.githubusercontent.com/9669492/210656561-ec32ae06-a45c-42e7-b8ac-2dc0d8a8c9a2.png)
```
SyntaxError: invalid identity escape in regular expression

[caused by minified script]
https://www.notion.so/app-3d6ac2f88b3223f5de94.js:1:4978895
```
... so **Notion** must've added that incompatible script in the interim 😡 ...

This breakage is **UXP-regex-parser** related, of course... 
[UXP #1286](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1286) hasn't yet made it into an **official** Pale Moon release, so the **Notion breakage** should be reproducible in current release **PM 31.4.2**...

**UXP forks** by **roytam1** have the new **UXP regex parser** (thanks **martok** ❤️ ) built-in since 2022-12-24; I have verified that "my" Notion URL **loads as expected** in the most-up-to-date **Serpent 52** (32-bit) **build** (BuildID=20221230024342) 🎉 ... 

I suppose **UXP #1286** will also supersede the `*.notion.*/postRender-*.js$script` fix, if **still relevant**...
