### ISSUE TITLE
SyntaxError: expected expression, got keyword 'import'

### ISSUE THREAD

**Issue by InterLinked1** [martok/palefill#43] opened 2022-08-31 13:42 UTC
Thanks for all the work everyone has done on this so far.

Would it be possible to polyfill (or transpile, if necessary), the "import" keyword?

Unfortunately, some sites seem to be using that in the browser now.

It's constant whack-a-mole these days with browser breakage and cleaning up everyone's mess.

```
SyntaxError: expected expression, got keyword 'import'
```

**Comment by martok** [comment] 2022-08-31 14:49
Duplicate of #34.

<details>
<summary>I've just re-tested with a minimal example, the keyword form works as expected.</summary>

index.html
```html
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>modules</title>
		<script type="module" src="showImport.js"></script>
	</head>
	<body>
     <button onclick="showImportedMessage()">Show</button>
	</body>
</html>
```

show.js
```js
export function showMessage() {
  alert("hello world");
}
```

showImport.js
```js
import {showMessage} from "./show.js"

window.showImportedMessage = function showImportedMessage() {
  showMessage();
}
```
</summary>

**Closed by martok** 2022-08-31 14:49 UTC
